version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Start test with QA Wolf
          command: |
            ## Start local server
            yarn serve & npx wait-on http://localhost:8080
            ## Start test
            npx qawolf test
          environment:
            QAW_ARTIFACT_PATH: /tmp/artifacts
            QAW_URL: http://localhost:8080

      - store_artifacts:
          path: /tmp/artifacts

